export const GET_TASKS = 'GET_TASKS'
export const GET_TASKS_STARTED = 'GET_TASKS_STARTED'
export const GET_TASKS_SUCCESSFUL = 'GET_TASKS_SUCCESSFUL'
export const GET_TASKS_FAILED = 'GET_TASKS_FAILED'

export const UPDATE_TASK = 'UPDATE_TASK'
export const UPDATE_TASK_STARTED = 'UPDATE_TASK_STARTED'
export const UPDATE_TASK_SUCCESSFUL = 'UPDATE_TASK_SUCCESSFUL'
export const UPDATE_TASK_FAILED = 'UPDATE_TASK_FAILED'

export const CREATE_TASK = 'CREATE_TASK'
export const CREATE_TASK_STARTED = 'CREATE_TASK_STARTED'
export const CREATE_TASK_SUCCESSFUL = 'CREATE_TASK_SUCCESSFUL'
export const CREATE_TASK_FAILED = 'CREATE_TASK_FAILED'
