export const ADD_EXISTING_TASK = 'ADD_EXISTING_TASK'
export const ADD_TASK = 'ADD_TASK'
export const GOT_TASKS = 'GOT_TASKS'
export const EDIT_TASK = 'EDIT_TASK'

export const GET_TASKS = 'GET_TASKS'
export const UPDATE_TASK = 'UPDATE_TASK'
export const CREATE_TASK = 'CREATE_TASK'
export const REMOVE_TASK = 'REMOVE_TASK'
export const REMOVED_TASK = 'REMOVED_TASK'
