export const ADD_SECTION = 'ADD_SECTION'
export const GOT_SECTIONS = 'GOT_SECTIONS'
export const EDIT_SECTION = 'EDIT_SECTION'

export const GET_SECTIONS = 'GET_SECTIONS'
export const UPDATE_SECTION = 'UPDATE_SECTION'
export const CREATE_SECTION = 'CREATE_SECTION'
export const REMOVE_SECTION = 'REMOVE_SECTION'
export const REMOVED_SECTION = 'REMOVED_SECTION'
